### ISSUE TITLE
RFC: PAL Project Ownership/Maintenance

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/pal#80] opened 2021-07-06 21:26 UTC
# Summary

This RFC seeks to gather feedback from the Bareflank community and maintainers about plans for maintenance and ownership of the PAL project, including an idea to transfer ownership of the PAL project to a new GitHub organization.

What are your thoughts @rianquinn @connojd @brendank310?

# Background Context

In 2018, The PAL project was started as a side project to the Bareflank Hypervisor, intended to provide a support library for manipulating system registers of Intel and ARMv8 CPUs. The goal was to reduce maintenance burden coming from Bareflank's "bfintrinsics" layer by developing a code generator, as opposed to hand-written accessor functions. Since then, the project has been used for numerous research efforts, but (to my knowledge) was never fully integrated into the Bareflank Hypervisor ecosystem (Hypervisor, MicroV, etc).

As of December 2020, The PAL project's primary contributor and maintainer (myself, Jared Wright) moved to a new employer (Amazon Web Services), where I would like to continue efforts to develop and maintain the project. In the short term, there are a couple hoops I need to jump though before I can do this, so I am looking to identify the best path for myself to contribute to PAL in open source. In the long term, I would also like to ensure the scope of the project is able to expand over time to include new features such as:
* Support for more programing languages (e.g. Rust)
* APIs for system instructions
* APIs for peripheral devices and data structures (e.g. ACPI tables, page tables, etc)
* Execution shims to enable forwarding of APIs across system boundaries (e.g. userspace->kernel via an IOCTL, much like how Chipsec works)
* Adoption and integration with a variety of open-source projects (e.g. AWS's [Kernel Test Framework](https://github.com/awslabs/ktf))
* Engagement with silicon vendors (e.g. Intel, AMD, etc) to seek contributions and maintenance of the project's register+instruction database.

# Proposed Changes

I'd like the current Bareflank maintainers to weigh in on which of the following strategies is most appropriate to support future development and maintenance of the PAL project. My personal recommendation is to pursue "Option 1".

I would also like to get a better understanding of the Bareflank community's current dependencies on (or future plans for) the PAL project to ensure everyone's needs are supported. At the moment, I am not aware of any integrations between PAL and another project in the Bareflank organization, but I'm wondering if there are other dependencies internally at AIS?

## Option 1: Move PAL to the [AWS Labs](https://github.com/awslabs) GitHub Organization

Pros:
* This is the easiest path for me to continue contributing to and maintaining the project.
* This is likely the easiest path for me to pursue more support for the project.
* The project could likely maintain its current license (MIT) or a similar one (Apache 2.0, or a more permissive MIT-0)

Cons:
* The project will likely need to go through a name change (there's a another PAL project [here](https://github.com/clinthuffman/PAL))
* The copyright for the project would likely need to be transferred from Assured Information Security, Inc to Amazon.
* Existing Bareflank maintainers would need to jump through hoops to become maintainers (I don't think this is a real problem, but want to make it explicit)

## Option 2: Keep PAL in the Bareflank GitHub organization (where it is now)

Pros:
* The project's maintainers and the governance model stays the same.
* Assured Information Security, Inc maintains the copyright to the project.

Cons:
* I'm not 100% certain if it is possible for me to contribute this way. The project's current CLA agreement may cause friction for me trying to contribute and maintain on behalf of my employer.
* This option will take some more research on my part.

## Option 3: Find another open source community that wants to adopt the project

I'm open to suggestions if anyone has another idea for a good "home" for PAL.

## Option 4: Maintain two project forks

I really hate this option, but I would be open to discussing if for some reason there is no other choice.

**Comment by rianquinn** [comment] 2021-07-06 21:57
@JaredWright Hey, nice to hear from you. Hope all is well. 

- Option 1: Not likely the best option. The code was developed by AIS, so simply transferring the copyright is not as simple as just re-marking the files. A donation of the code would have to be made officially to Amazon in this case which would be far more difficult I would think when compared to Option 2. 
- Option 2: My preference. The CLA is only there to deal with the lack of patent protection with MIT, so if Apache 2.0 is easier, we could just change the license to make it easier to contribute to. I don't think anyone is concerned with how the code is used, but simply with protecting both AIS and people using the code from weird issues like silly lawsuits. Either way, let us know what else we can do to help. 
- Option 3: I don't think this is needed. If a donation has to occur, it's going to be a pain no matter what, so in this case I think AWS would be the better option if this is required. 
- Option 4: Agreed... this is a terrible option.

**Comment by JaredWright** [comment] 2021-07-07 22:15
Ahh, it makes total sense this would be the scenario: Option 1 is a pain for AIS, while Option 2 is a pain for me. 😁 

It just occurred to me that there might also be an Option 1.5 (right in between the first two). Since this project is licensed MIT, it would be possible to migrate the repository to a new GitHub organization (like option 1), but propagate the AIS copyright along with the project (like Option 2), so that the project (after migration) has multiple copyright holders while retaining the same license. Thoughts on that Option 1.5? If that doesn't work, I'll start looking more into the steps on my side to pursue Option 2.

I'm glad we agree that Option 4 is terrible.

**Comment by JaredWright** [comment] 2021-07-07 22:35
I guess there might be another variation in between Option 1 and Option 2 (maybe call it 1.5.2?): Since AIS holds the copyright to this project, could they re-license it to an even more permissive [MIT-0](https://github.com/aws/mit-0) (MIT minus the attribution requirement). I think that would enable a migration (like Option 1) without the need for attribution or a code donation. This has the obvious downside of AIS giving up the credit for developing the project though (which isn't ideal in my opinion).

**Comment by rianquinn** [comment] 2021-07-07 23:38
@JaredWright yeah... hahahah, isn't that always how it works! 

Not a huge fan of MIT-0. Option 1.5 is just a fork at the end of the day which is not ideal, but anyone is welcome to do that of course.

**Comment by JaredWright** [comment] 2021-07-08 14:49
Right, I was implicitly suggesting to deprecate this repository as part of Option 1.5 (making it different from Option 4). I was also under the assumption that there aren't any Bareflank or AIS projects that use this repository (at a quick glance, I don't see any dependencies in hypervisor or microv).

Is the Bareflank community planning to make use of this project? If so, leaving it here definitely seems the right way to go. I didn't intend to suggest that Bareflank abandons the project, I just didn't think it was being used by this community at all.

**Comment by connojd** [comment] 2021-07-13 18:20
@JaredWright What about the CLA makes it difficult to contribute changes to? I think if a barrier exists because of the CLA, it should be updated for every BF project, not just PAL, because the other projects might run into similar difficulties in the future.

If modifying the CLA is not enough, then I think Option 1.5 makes the most sense. It wouldn't be a fork as @rianquinn suggested, because a fork implies at least two streams of active development, and I'm not aware of any plans to use PAL for the new microkernel stuff moving forward or any other bareflank projects. @rianquinn and @brendank310 may have plans to use it I'm unaware of though.

**Comment by rianquinn** [comment] 2021-07-13 19:38
@JaredWright / @connojd So it is not really an issue of who is using the code or not. I definitely want to use it in the hypervisor logic as right now, we are duplicating a lot of code that PAL can address automatically. We just haven't done the integration yet because it's not the highest priority issue at the moment. 

The bigger issue with Option 1.5 is the loss of attribution. AIS funded the initial work and currently owns the copyright. The reason I suggested Apache 2.0 is that it addresses the patent issue without having to have someone sign something which could be a problem for people (although using Apache 2.0 has other issues which is why we didn't use it in the first place).  

By no means do I think it is a good idea to give up attribution or copyright without an official donation. AIS should get at least a little credit for the work.

**Comment by JaredWright** [comment] 2021-07-13 20:40
@connojd I believe the only difficulty associated with the CLA on my end is the fact that it exists (requires a legal review for me to go through, regardless of what the CLA actually says).

@rianquinn I don't believe that Option 1.5 would result in AIS giving up any attribution or copyright. Instead, the AIS copyright would propagate forwards (under the conditions of MIT), and the project would end up with two copyright holders.

It sounds like we're all trending toward either Option 2 (leave the repo here) or Option 1.5 (migrate with dual copyright holders), so how about this: I'll simultaneously start going through steps on my end to pursue both options, and will continue to update everyone here with roadblocks as I encounter them.

**Comment by rianquinn** [comment] 2021-07-13 20:52
I definitely like Option 2 best. We did some research, and Amazon contributes to a lot of open source projects that contain a CLA including Kubernetes and Apache. It's pretty common practice, even with other open source licenses to require a CLA (it just so happens that we use it for patent issues with MIT), but again, if that is an issue, I would be open to changing to Apache 2.0 if that helps. 

Option 1.5 was to use MIT-0, which specifically removes attribution requirements which is why I don't like it. If the plan is to just fork PAL to AWS and then everyone works on the project from there and nothing else changes, I question why that is needed in the first place (would be like me going to Microsoft and saying, see this project over here that you don't seem to be using right now at this exact moment... yeah, can I move it to our organization and then you work on it from there?) 

Now with all of that said, I want to see movement on the project because it is a big deal for research, so if there is interest on your end, or even Amazon's, I want to ensure continued work can be done in a way that supports your needs, and I certainly don't want to make your life more difficult. I just don't want AIS getting screwed in the process. 

Ideally, Option 2 (even if a license change to Apache 2 is required) is what I would prefer.

**Comment by connojd** [comment] 2021-07-13 22:17
@rianquinn @JaredWright I think MIT-0 was for Option 1.5.2 :smile:. Option 1.5 IIUC proposes two things: move the project to AWS and add AWS as a copyright holder, without removing AIS's copyright. I'm personally fine with that approach if that is all that it entails.

**Comment by rianquinn** [comment] 2021-07-13 22:59
That's not really how copyright works. Amazon cannot be a copyright holder of PAL unless AIS donates PAL officially to Amazon. It's a legal process to transfer copyright meaning AIS and Amazon's legal teams would have to be involved. Amazon is free to add or modify PAL, and those modifications are subject to the current copyright holder's CLA. In the case of Bareflank, AIS maintains the copyright of any work contributed to the project. When you don't do that, you end up with issues that for example LLVM has where a change to the license requires all copyright holders to agree (and when they get diverse enough, that can be really hard to do). But that is a possibility. Assuming the modifications are large enough, and if the CLA/license allows it, the contributor can add their copyright to the file being modified. 

So in other words, moving the project to AWS's organization does not give AWS copyright claims to the project. AIS still owns 100% of the copyright, Amazon owns 0%. It just lives on a different GitHub page. For Amazon to have copyright claim to the source code AIS either needs to donate the code, or AIS needs to drop the copyright requirement from the CLA, and Amazon needs to contribute to the project. Amazon would only have a copyright claim on the additions and modifications that it made. The other option is Amazon forks PAL. In that case, AIS still owns 100% of the copyright, but on the forked project, Amazon would own the copyright to any mods and additions it made to it's fork. 

This gets even more insane when you realize that in most states, your employer owns the copyright to all of the work you do, whether it is on the clock or not, something Amazon is taking a fair amount of beef for right now as the news is reporting that any game you make as an Amazon employee after hours Amazon owns and has the right to sell themselves, even if they had nothing to do with it. People went nuts over that, but right now in a lot of states, that is actually legally allowed.... even if it is totally messed up. 

That's why I like option 2 the best. Change the license so that the CLA is no longer needed. For PAL specifically, we can drop the copyright goes to AIS requirement (assuming Chuck agrees), allowing Amazon to add their copyright to any file they modify or add (actually any file they add would only contain Amazon's copyright), and we are done. I don't see the benefit of moving the repo to a different organization. This way there is nothing to sign, Amazon maintains the copyright to anything they contribute, and AIS is still in the mix. The only thing we need to be sure of is the license as once Amazon has a copyright claim on some of the code, any license changes from that point on would need approval from Amazon as well as AIS, which again, gets hard to do, so you kind of want to get it right the first time. Especially if anyone else joins in.

**Comment by hyandell** [comment] 2021-07-15 00:33
Just wanted to say Hi. I'm a part of the OSPO at AWS and Jared has connected with us. The current state is that I'd like to see a copy of the CLA as the link provided results in a empty file. Just so it's clear though, I'm not a lawyer, so I wouldn't be interpreting that text on my own. 

As AWS was one of the pioneers of MIT-0, I also wanted to +1 @rianquinn's comments on it. MIT-0 is a great license for sample code that is going into a user's codebase, but I would expect to rarely use it for a reusable library. Probably not a good fit here.

**Comment by rianquinn** [comment] 2021-07-15 00:54
@hyandell It is great to meet you. Not sure why you are seeing a blank page. Will have to check on the plumbing there to see what the issue is. For now, this is the CLA we use (this is actually one that was just signed today by another contributor to the hypervisor):

https://cla-assistant.io/Bareflank/hypervisor?pullRequest=950

So that is what you should be seeing. We used CLA assistant to create this, and as stated above, it really only has two goals. Ensure that the contributor cannot sue AIS for patent infringement on things they contribute, and that AIS maintains the copyright of all contributed works to ensure there is a single copyright holder. For PAL, if that is an issue removing the CLA and changing to Apache 2.0 is an option.

**Comment by hyandell** [comment] 2021-07-16 20:42
Thanks Rian. That worked, and it looks like a standard Apache ICLA, adjusted for different project naming. I don't see us having an issue there, our folk are agreeing to Apache ICLAs all the time.

[Taking off my AWS OSPO hat and switching to my member of Apache Software Foundation licensing-opinion hat where I can be a bit more authoritative in ICLA opinion]
It's not making AIS a single copyright holder, it's giving AIS a simple copyright-license to every contribution. That's how we handle things at the ASF too. It allows us to do things like relicensing, without having to deal with copyright-assignment issues. Also, much appreciated how you put a note at the end of the CLA saying it was modeled after the ASF one :) It's always nice when folk do this right. Feels too often that folk edit the CLA all over the place, then leave the Apache title on it.

[Back to the AWS hat]
Not being copyright-assignment is awesome, because copyright reassignment is a big palaver process wise in terms of approvals and signatures, whereas licensing something under basically Apache-2.0 is done every day. 

Anyways, I hope it wasn't too jarring for me to speak with two voices, and I'll get back to understanding the business side of things internally so I can help guide Jared.

**Comment by rianquinn** [comment] 2021-07-16 21:07
@hyandell Awesome, and yeah my bad for the misleading language there. That's exactly what we are trying to do there. We don't actually care who has copyright to contributions that AIS doesn't make, but rather that AIS is one of the copyright holders of the contributed work specifically so that relicensing, reuse, etc is not an issue. Again, don't want to end up like LLVM where you have to get hundreds of people to sign off on a license change if it is ever needed in the future.

**Comment by JaredWright** [comment] 2021-08-20 21:49
Happy Friday everyone! It took a bit of back-and-fourth, but we are all clear to proceed with Option 2 from AWS's perspective. The project will continue to operate exactly as it is now, no updates to the license or CLA are needed. Now for the fun part: get ready for a flood of contributions! 😎

**Closed** 2021-08-20 21:49 UTC
